/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HardwareMonitor */

#ifndef _Included_HardwareMonitor
#define _Included_HardwareMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HardwareMonitor
 * Method:    Initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HardwareMonitor_Initialize
  (JNIEnv *, jobject);

/*
 * Class:     HardwareMonitor
 * Method:    GetCPUTemperature
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_HardwareMonitor_GetCPUTemperature
  (JNIEnv *, jobject);

/*
 * Class:     HardwareMonitor
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HardwareMonitor_Close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
